# -*- coding: utf-8 -*-
"""W19e: power analysis v2 (realistic signal shape) + aggregation-artifact check.

Exp B2 — Power v2: instead of a random 43-dim direction (adversarial worst
case, v1), the planted signal is the NCP-wide environmental response model's
prediction on the Pinggu grids — i.e. "what if Pinggu's true yields were
generated by the regional environment-yield response that our framework
recovers at R2=0.69 nationally". Feature spaces differ (24 Pinggu vars vs 24
NCP cols), so we train on the SHARED feature columns only.
Exp C — 1-km artifact check: sample 20k raw History fine cells, attach the
same coarse features, CV. If R2 at the fine level is close to 0.69, the
national result is not an aggregation-smoothing artifact.
Outputs: w19_power_analysis_v2.csv, w19_finelevel_check.csv
"""
import os, warnings
import numpy as np, pandas as pd
warnings.filterwarnings("ignore")
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score
from xgboost import XGBRegressor

ROOT = r"D:\2026-SP"; INT = os.path.join(ROOT, "Outputs", "intermediate")
SEEDS = [7, 21, 42]
NEW = dict(n_estimators=428, max_depth=5, learning_rate=0.168, subsample=0.594,
           colsample_bytree=0.821, min_child_weight=6, reg_alpha=3.57, reg_lambda=2.69,
           random_state=42, n_jobs=1, verbosity=0)

def bio_name(c):  # unify column names: wc2.1_2.5m_bio_12 -> bio12
    return c.replace("wc2.1_2.5m_", "")

NAT = pd.read_csv(os.path.join(INT, "w19_national_grid_features.csv"))
E = pd.read_csv(os.path.join(INT, "data_with_yield_ensemble_full.csv"))
# explicit name bridge: Pinggu ensemble <-> NCP feature table
BRIDGE = {f"bio{i}": f"wc2.1_2.5m_bio_{i}" for i in range(1, 20)}
BRIDGE.update({"clay_pct": "clay", "sand_pct": "sand", "soc_dgkg": "soc",
               "bdod_kgdm3": "bdod", "cec_cmolkg": "cec", "ph": "phh2o"})
shared = [c for c in BRIDGE if c in E.columns and BRIDGE[c] in NAT.columns]
shared = sorted(set(shared))
print("shared feature cols:", len(shared), shared[:5], "...", flush=True)

# ---------- shared-feature NCP model (response shape donor) ----------
F = NAT.rename(columns={v: k for k, v in BRIDGE.items()})
FE = shared
Xn, yn = F[FE].values.astype(float), F["y"].values.astype(float)
resp = np.zeros(len(yn))
for tr, te in KFold(5, shuffle=True, random_state=42).split(Xn):
    m = XGBRegressor(**NEW).fit(Xn[tr], yn[tr]); resp[te] = m.predict(Xn[te])
print(f"[donor] NCP shared-feature CV R2 = {r2_score(yn, resp):.4f}", flush=True)
donor = XGBRegressor(**NEW).fit(Xn, yn)  # full-data response model

# ---------- Exp B2: power v2 on Pinggu 43 grids ----------
yA = E["wheat_yield_tha"].values; mA = ~np.isnan(yA)
drop = {"lon","lat","wheat_yield_tha","wheat_yield_pred_tha","yield_uncertainty_tha",
        "yield_source","yield_blended_tha","yield_source_blend"}
FE24 = [c for c in E.columns if c not in drop and E[c].dtype in ("float64","int64")]
XA = E.loc[mA, FE24].values.astype(float)
XA_shared = E.loc[mA, shared].values.astype(float)   # donor feature space (25 cols)
sig_raw = donor.predict(XA_shared)
sig = (sig_raw - sig_raw.mean()) / (sig_raw.std() + 1e-12)   # z-scored signal shape
y_sd = float(np.nanstd(yA[mA]))
N_SIM = 200
rows = []
for r2pop in [0.05, 0.10, 0.20, 0.30, 0.50]:
    sigma = y_sd*np.sqrt(1-r2pop)
    det05 = det10 = 0; r2s = []
    for s_i in range(N_SIM):
        eps = rng = np.random.default_rng(1000+s_i).normal(0, sigma, XA.shape[0])
        y = sig*y_sd*np.sqrt(r2pop) + eps
        yp = np.zeros(len(y))
        for tr, te in KFold(5, shuffle=True, random_state=s_i).split(XA):
            m3 = XGBRegressor(**NEW).fit(XA[tr], y[tr]); yp[te] = m3.predict(XA[te])
        r2 = r2_score(y, yp); r2s.append(r2)
        det05 += r2 > 0.05; det10 += r2 > 0.10
    rows.append({"r2_pop": r2pop, "n_sim": N_SIM,
                 "det_rate_r2gt0.05": round(det05/N_SIM, 3),
                 "det_rate_r2gt0.10": round(det10/N_SIM, 3),
                 "median_r2": round(float(np.median(r2s)), 4),
                 "signal_shape": "NCP response-model prediction on Pinggu grids (realistic)"})
    print(f"[B2] R2pop={r2pop}: median {np.median(r2s):.3f} det(>0.05)={det05/N_SIM:.2f} det(>0.10)={det10/N_SIM:.2f}", flush=True)
pd.DataFrame(rows).to_csv(os.path.join(INT, "w19_power_analysis_v2.csv"), index=False)

# ---------- Exp C: fine-level (1 km) artifact check ----------
print("[C] fine-level check ...", flush=True)
import pyreadr, rasterio
from rasterio.warp import transform as warp_transform
df = list(pyreadr.read_r(os.path.join(ROOT, "Data", "Management", "Xiao2024", "Allregions.rds")).values())[0]
h = df[df["Period"] == "History"][["gridcell", "Yield"]].sample(20000, random_state=7).copy()
del df
LON0, LAT1, RES1, NCOL = 112.1, 40.7, 0.008333333333333333, 1320
g = h["gridcell"].values
h["lon"] = LON0 + (g % NCOL)*RES1; h["lat"] = LAT1 - (g // NCOL)*RES1
BIO = [f"wc2.1_2.5m_bio_{i}" for i in range(1, 20)]
soil_dir = os.path.join(ROOT, "Data", "SoilGrids_wgs84")
soil_t = []
for v in ["clay","sand","soc","bdod","cec","phh2o"]:
    soil_t += [os.path.join(soil_dir, f) for f in os.listdir(soil_dir) if f.startswith(v+"_0-5cm")][:1]
def sample_batch(tifs, lons, lats):
    out = np.full((len(lons), len(tifs)), np.nan, dtype=np.float32)
    for j, p in enumerate(tifs):
        try:
            with rasterio.open(p) as s:
                xs, ys = lons, lats
                if s.crs and s.crs.to_string() != "EPSG:4326":
                    xs, ys = warp_transform("EPSG:4326", s.crs, list(map(float, lons)), list(map(float, lats)))
                vals = np.array([r[0] for r in s.sample(zip(xs, ys))], dtype=np.float64)
                if s.nodata is not None: vals[vals == s.nodata] = np.nan
                out[:, j] = vals
        except Exception: pass
    return out
Xb = sample_batch([os.path.join(ROOT, "Data", "WorldClim", f"{b}.tif") for b in BIO], h["lon"].values, h["lat"].values)
Xs = sample_batch(soil_t, h["lon"].values, h["lat"].values)
FF = pd.DataFrame(np.hstack([Xb, Xs]), columns=BIO + [os.path.basename(p).split("_0-5cm")[0] for p in soil_t])
FF["y"] = h["Yield"].values
FF = FF.dropna(axis=1, how="all").dropna()
Xf, yf = FF.drop(columns=["y"]).values.astype(float), FF["y"].values.astype(float)
ps = []
for tr, te in KFold(5, shuffle=True, random_state=42).split(Xf):
    m4 = XGBRegressor(**NEW).fit(Xf[tr], yf[tr]); ps.append(r2_score(yf[te], m4.predict(Xf[te])))
res = {"n_fine": len(FF), "fine_cv_r2_folds": [round(p, 4) for p in ps],
       "fine_cv_r2_mean": round(float(np.mean(ps)), 4),
       "note": "20k raw 1-km History cells, same coarse-resolution features; guards against aggregation smoothing"}
pd.DataFrame([res]).to_csv(os.path.join(INT, "w19_finelevel_check.csv"), index=False)
print(f"[C] fine-level R2 = {np.mean(ps):.4f} (n={len(FF)})", flush=True)
print("W19e done")
